spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      ds1:
        url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
        username: root
        password: root
      ds2:
        url: jdbc:mysql://localhost:3306/test1?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
        username: root
        password: root
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 12000000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 2000
      time-between-eviction-runs-millis: 12000000   # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        stat: # 监控配置
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 1000
        wall: # 防火墙配置
          config:
            multi-statement-allow: true
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        allow: 127.0.0.1,10.1.1.28 # ip 白名单
        deny: 10.1.1.29  # ip黑名单 同时存在优先级大于 allow
        reset-enable: false # 禁用HTML页面上的rest all 功能
        login-username: admin
        login-password: 123456

  cache:
    ehcache:
      config: classpath:cache/ehcache.xml #制定配置文件路径
    type: ehcache
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000
  activiti:
    check-process-definitions: false #设置为不校验 processes 文件 .bpmn
    database-schema-update: false # 配置应用启动是否检查Activiti数据表 false 标识不检查，以提高启动速度
    history-level: full #保存历史数据级别设置为full最高级别，便于历史数据的追溯
logging:
  config: classpath:logback-spring.xml